FROM node:20

WORKDIR /usr/src/app

RUN npm install -g bun
COPY prisma package*.json bun.lockb ./
RUN bun install --frozen-lockfile
RUN bun generate
COPY . .

ENV NODE_ENV production

CMD ["bun", "migrate-and-start:prod"]