services:
  nodb-app:
    image: nodb-app
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodb-network
  postgres:
    image: pgvector/pgvector:pg16
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
networks:
  nodb-network:
    driver: bridge
volumes:
  postgres_data: