services:
  nodb-app:
    build:
      dockerfile: Dockerfile.dev
    image: nodb-app
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nodb-network

  mongo:
    image: mongodb/atlas
    privileged: true
    command: |
      /bin/bash -c "atlas deployments setup --type local --port 27778 --bindIpAll --username root --password 1234567 --force && tail -f /dev/null"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 27778:27778

volumes:
  nodb:

networks:
  nodb-network:
    driver: bridge