services:
  nodb-app:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    image: pgvector/pgvector:pg16
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: