FROM postgres:16

RUN apt-get update && apt-get install -y \
    build-essential \
    postgresql-server-dev-16 \
    git

RUN git clone https://github.com/pgvector/pgvector.git

RUN cd pgvector && \
    make && \
    make install

RUN echo "shared_preload_libraries = 'pgvector'" >> /usr/share/postgresql/postgresql.conf.sample